### ISSUE TITLE
github.com/alaaProg/postapi/models seems missing.

### ISSUE THREAD

**Issue by UlasSAYGINIM** [alaa-aqeel/fiber-api-example#1]
if i am not wrong , github.com/alaaProg/postapi/models seems not exist.
can you check it?

thank you.

**Comment by alaa-aqeel** [comment]
It exists [https://github.com/AlaaProg/fiber-api-example/tree/master/models](https://github.com/AlaaProg/fiber-api-example/tree/master/models)

**thx for the first issues**

**Comment by UlasSAYGINIM** [comment]
you are welcome. can you look this and can you say that is it right import?
https://github.com/AlaaProg/fiber-api-example/blob/master/controller/AccountController.go
i see this. am i wrong? and this repo does not exist. "github.com/alaaProg/postapi/models"

**Comment by alaa-aqeel** [comment]
Yes, it is wrong to call the repo a different name than the module. But it's working 
I need to change this repo name to PostAPI or update all imports.

**Comment by UlasSAYGINIM** [comment]
thank you for information. i just wondered that what that repo has (github.com/alaaProg/postapi) because it is deleted.
